apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- applications.yaml
- helmrelease-argocd.yaml
- helmrelease-ingress-nginx.yaml
- helmrelease-metallb.yaml
- helmrelease-monitoring.yaml
- helmrepository.yaml
