apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/thiscluster/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

