---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: thiscluster
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/thiscluster/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

