apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
  name: temporal
  namespace: flux-system
spec:
  timeout: 20m
  chart:
    spec:
      chart: temporal
      sourceRef:
        kind: HelmRepository
        name: adonai
      version: 0.35.0
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  interval: 5m
  releaseName: temporal
  storageNamespace: temporal
  targetNamespace: temporal
  values:
    server:
      replicaCount: 1
    cassandra:
      config:
        cluster_size: 1
    prometheus:
      enabled: true
    grafana:
      enabled: true
    elasticsearch:
      enabled: true

    schema:
      setup:
        enabled: false
        backoffLimit: 1000
      update:
        enabled: false
        backoffLimit: 1000
---

