apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-internal
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ingress-nginx-internal
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.8.3
    chart: ingress-nginx
    helm:
      parameters:
        - name: controller.ingressClassResource.controllerValue
          value: k8s.io/ingress-nginx-internal
        - name: controller.ingressClass
          value: nginx-internal
        - name: controller.ingressClassResource.name
          value: nginx-internal
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true

