apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporalio
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: temporalio
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/temporal
    repoURL: 'https://github.com/temporalio/helm-charts'
    targetRevision: HEAD
    helm:
      parameters:
        - name: prometheus.enabled
          value: 'false'
        - name: grafana.enabled
          value: 'false'
        - name: server.replicaCount
          value: '1'
        - name: cassandra.config.cluster_size
          value: '1'
        - name: elasticsearch.enabled
          value: 'false'
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
