apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporalio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://go.temporal.io/helm-charts'
    targetRevision: 0.36.0
    helm:
      parameters:
        - name: cassandra.config.cluster_size
          value: '1'
    chart: temporal
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: temporalio
  syncPolicy:
    automated: {}
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - PrunePropagationPolicy=background        
